networks:
    site01:
    site01db:

services:
    webserver:
        container_name: webserver
        build:
            context: ./nginx
        depends_on:
            - wordpress
        ports:
            - 8080:80
        networks:
            - site01
    wordpress:
        container_name: wordpress
        hostname: example.com
        image: wordpress:6-php8.1-apache
        depends_on:
            - mysql
        environment:
            WORDPRESS_DB_HOST: mysql
            WORDPRESS_DB_USER: username
            WORDPRESS_DB_PASSWORD: password
            WORDPRESS_DB_NAME: wordpress
        networks:
            - site01
            - site01db
    mysql:
        container_name: mysql
        image: mysql:8.4
        ports:
          - 3306:3306
        environment:
            MYSQL_DATABASE: wordpress
            MYSQL_USER: username
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
            MYSQL_RANDOM_ROOT_PASSWORD: "0"
        networks:
            - site01db
    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin:5
        ports:
            - 8081:80
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_USER: username
            PMA_PASSWORD: password
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
        networks:
            - site01db
