name: build and deploy

on:
    workflow_dispatch:

    push:
        branches:
            - main

jobs:
    secrets:
        runs-on: ubuntu-22.04

        permissions: write-all

        steps:
            - id: changelog_generator
              uses: heinrichreimer/action-github-changelog-generator@v2.3
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  unreleased: false

            - id: tag_version
              uses: mathieudutour/github-tag-action@v6.2
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  default_prerelease_bump: false

            - id: site01NginxMeta
              uses: docker/metadata-action@v5
              with:
                  flavor: |
                      latest=false
                  images: |
                      ghcr.io/hirbod-codes/site01/nginx
                  tags: |
                      type=schedule
                      type=ref,event=branch
                      type=ref,event=pr
                      type=semver,pattern={{version}},value=${{ steps.tag_version.outputs.new_version }}
                      type=semver,pattern={{major}}.{{minor}},value=${{ steps.tag_version.outputs.new_version }}
                      type=semver,pattern={{major}},value=${{ steps.tag_version.outputs.new_version }}
                      type=sha

            - uses: actions/checkout@v4

            - uses: docker/setup-qemu-action@v3

            - uses: docker/setup-buildx-action@v3

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - uses: docker/build-push-action@v6
              with:
                  context: ./nginx
                  file: Dockerfile
                  push: true
                  tags: ${{ steps.site01NginxMeta.outputs.tags }}
                  labels: ${{ steps.site01NginxMeta.outputs.labels }}

            - uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.SSH_SERVER_ADDRESS }}
                  port: ${{ secrets.SSH_SERVER_PORT }}
                  username: ${{ secrets.SSH_SERVER_USERNAME }}
                  password: ${{ secrets.SSH_SERVER_PASSWORD }}
                  script: |
                      mkdir -p swarm/site01/mongodb/data
                      docker stack rm site01
                      docker secret rm SITE01DB_USERNAME SITE01DB_PASSWORD
                      echo "${{ secrets.SITE01DB_USERNAME }}" | docker secret create SITE01DB_USERNAME -
                      echo "${{ secrets.SITE01DB_PASSWORD }}" | docker secret create SITE01DB_PASSWORD -
                      sleep 5s

            - uses: appleboy/scp-action@v0.1.7
              with:
                  host: ${{ secrets.SSH_SERVER_ADDRESS }}
                  port: ${{ secrets.SSH_SERVER_PORT }}
                  username: ${{ secrets.SSH_SERVER_USERNAME }}
                  password: ${{ secrets.SSH_SERVER_PASSWORD }}
                  source: "./swarm.yml"
                  target: ~/swarm/site01/

            - uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.SSH_SERVER_ADDRESS }}
                  port: ${{ secrets.SSH_SERVER_PORT }}
                  username: ${{ secrets.SSH_SERVER_USERNAME }}
                  password: ${{ secrets.SSH_SERVER_PASSWORD }}
                  script: |
                      cd swarm/site01
                      docker stack rm site01
                      tag=${{ steps.tag_version.outputs.new_version }} docker stack deploy --prune --detach=true --with-registry-auth -c swarm.yml site01

            - id: create_release
              uses: softprops/action-gh-release@v1
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  tag_name: ${{ steps.tag_version.outputs.new_tag }}
                  name: Release ${{ steps.tag_version.outputs.new_tag }}
                  body: ${{ steps.changelog_generator.outputs.changelog }}
                  draft: false
                  prerelease: false
