name: sync image

on:
    workflow_dispatch:

jobs:
    secrets:
        runs-on: ubuntu-22.04

        permissions: write-all

        steps:
            - id: changelog_generator
              uses: heinrichreimer/action-github-changelog-generator@v2.3
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  unreleased: false

            - id: tag_version
              uses: mathieudutour/github-tag-action@v6.2
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  default_prerelease_bump: false

            - id: site01NginxMeta
              uses: docker/metadata-action@v5
              with:
                  flavor: |
                      latest=false
                  images: |
                      ghcr.io/hirbod-codes/site01/nginx
                      http://${{ secrets.SSH_SERVER_ADDRESS }}:1501/hirbod-codes/site01/nginx
                  tags: |
                      type=schedule
                      type=ref,event=branch
                      type=ref,event=pr
                      type=semver,pattern={{version}},value=${{ steps.tag_version.outputs.new_version }}
                      type=semver,pattern={{major}}.{{minor}},value=${{ steps.tag_version.outputs.new_version }}
                      type=semver,pattern={{major}},value=${{ steps.tag_version.outputs.new_version }}
                      type=sha

            - uses: actions/checkout@v4

            - uses: docker/setup-qemu-action@v3

            - uses: docker/setup-buildx-action@v3

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - uses: docker/build-push-action@v6
              with:
                  context: ./nginx
                  file: ./nginx/Dockerfile
                  push: true
                  tags: ${{ steps.site01NginxMeta.outputs.tags }}
                  labels: ${{ steps.site01NginxMeta.outputs.labels }}
